# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

group :development do
  gem "rubocop", ">= 1.57.2", require: false
  gem "rubocop-rspec", ">= 2.25.0", require: false
end

group :test do
  gem "rspec", ">= 3.12.0"
end
